### ISSUE TITLE
Methods that return an array do not work in a {{#method}} section

### ISSUE THREAD

**Issue by aaminoff** [CliffS/mustache-simple#4]
[mustache-simple-meth-ary.txt](https://github.com/CliffS/mustache-simple/files/1174692/mustache-simple-meth-ary.txt)

It appears that if a method call returns an array, the {{#method}} ... {{/method}} is replaced in its entirety by the string overload of the first element of the array.

As an additional feature request, in our large code base we have methods that return arrays and methods that return arrayrefs. It seems reasonable to say that the correct behavior with an arrayref is to dereference it and continue as if it were an array.

Edit: I wrote a test script to illustrate the desired behavior

**Comment by aaminoff** [comment]
I modified the module to handle this case. It passes my test as well as all the old tests, but I have the suspicion that my modifications might break a behavior that the original use relied upon.

I have never submitted a PR to an open source project before, so I will read up on how to do that before attempting it.

**Comment by CliffS** [comment]
I'll look forward to the PR.

Of interest, does it work if each of the elements of the array is a simple hash rather than a blessed object?

**Comment by aaminoff** [comment]
Yes, that works too. I added that case to my test. OK, so now I will work on the PR.

**Comment by aaminoff** [comment]
We fixed this, so can I close it? I think so.
