### ISSUE TITLE
triple-bracket intermittently fails to un-escape html

### ISSUE THREAD

**Issue by aaminoff** [CliffS/mustache-simple#6]
This may be some weird bug in Apache or Perl rather than Mustache::Simple.

I have a long {{#listing}} which includes some {{{methods}}} that are processed by Mustache::Simple. A triple-bracket is supposed to pass html through unchanged. Sometimes all the {{{method}}} calls end up escaped (html is rendered as &lt;tag etc), and sometimes, even more oddly, the first several show up correctly but then at a certain point halfway through the listing the rest switch to escaped. It is always at the same place, but there is nothing I can figure out about the data that would make this happen, and why does it change as you refresh the page?

The page in question is public, try 

http://wwwdev.nber.org/sched/si17

I am also seeing 

`Use of uninitialized value $_ in pattern match (m//) at /usr/local/lib/perl5/site_perl/Mustache/Simple.pm line 325.
`

but I can not establish that that is happening only when the problem occurs - it could just be a useless warning. Still, it seems odd that something would reach that point in the code without $tag{type} being set. I am running with Mustache::Simple 1.36 on FreeBSD 11.1 with mod_perl/2.0.10 Perl/v5.24.1 on Apache 2.4.27

**Comment by CliffS** [comment]
I am guessing that this is something to do with breaking changes in Perl 5.24 but I'm looking now.

**Comment by CliffS** [comment]
@aaminoff Are you able to replace the `given` on line 318 of `/usr/local/lib/perl5/site_perl/Mustache/Simple.pm` with `for`?

I would be most interested whether that solves your problem.  Please let me know.

**Comment by aaminoff** [comment]
I did try that (along with a couple other changes, replacing break with 
last). It did not solve the triple-bracket problem. I am not sure if the 
triple-bracket problem is correlated with the messages about 
uninitialized $_.

**Comment by CliffS** [comment]
OK.  Is it possible for me to get a copy of the mustache template that is failing to render?

**Comment by aaminoff** [comment]
I put the template here:

http://wwwdev.nber.org/~aminoff/master.dev.mtmpl

Unfortunately the perl code that backs it is pretty complicated.

#listing is an array of NBER::Schedule::Item objects or hashes.

is_hash is a hash element that is set to 1 if it is a hash, but there is 
no method is_hash defined on the paper object, so ^is_hash happens for 
objects.

confids_links is a method that returns some html that is defined and 
returns something for most paper objects. For example:

<a href="http://wwwdev.nber.org/sched/SI17IFM">IFM</a>

**Comment by aaminoff** [comment]
It appears that the error messages

Use of uninitialized value $_ in pattern match (m//) at 
/usr/local/lib/perl5/site_perl/Mustache/Simple.pm line 328.

happen just when the un-escaped bug occurs.


1) Open a new browser tab

2) go to the exact URL:

http://wwwdev.nber.org/sched/si17?dates=2017-07-13&submit=Go%21&r=

There are 29 items listed, and each one has escaped html instead of 
unescaped html in the second column. When I do that, I see in the apache 
error log 29 error messages about uninitialized value.

3) Hit reload, possibly several times

Eventually a page will appear with the html un-escaped (as it should 
be). When that happens, in my error log I see no uninitialized error 
messages.

The different behavior when you reload suggests something having to do 
with cacheing. Or does Mustache::Simple somehow inadvertently use a 
global variable? (You are not supposed to do that under mod_perl I 
believe). Or it has to do with a strange interaction between apache and 
mod_perl and Mustache::Simple.

If you want to send me a version of Mustache::Simple with debugging warn 
statements inserted I can try to run with that. I tried to do a little 
of that myself but quickly got in over my head.

**Comment by CliffS** [comment]
@aaminoff For the template you sent me, are you able to output the context (maybe with Data::Dumper) just before it gets rendered?

I'm not going to get a chance to look at this any more this evening but I'll make it top priority for the morning.

**Comment by aaminoff** [comment]
On 04/01/2018 02:13 PM, Cliff Stanford wrote:
>
> @aaminoff <https://github.com/aaminoff> For the template you sent me, 
> are you able to output the context (maybe with Data::Dumper) just 
> before it gets rendered?
>

Here is the simple version, with Data::Dumper::Maxdepth = 3

http://wwwdev.nber.org/~aminoff/ms_bug_good.dump.txt

http://wwwdev.nber.org/~aminoff/ms_bug_bad.dump.txt

bad means when the html is escaped.

Unfortunately confids_links is a method on NBER::Schedule::Item so you 
can not see it directly until it is called, later.

**Comment by CliffS** [comment]
I'm now pretty sure that this is not related to a bug in `Mustache::Simple` but is to do with Apache cacheing.  It's probably something to do with the individual items you're pulling off, `NBER::Schedule::Item`.  When these resolve, do they contain any `{{` or `{{{`?

I'm afraid it was this kind of cacheing problem that put me off mod_perl; I now run everything on nginx with fastcgi.  I've tried `speedy` but didn't find it made enough difference to be worth it for my sites.

Is it possible for you to move this from mod_perl to a CGI temporarily?  It may slow it down but it will prove whether it's a mod_perl issue.

**Comment by aaminoff** [comment]
OK, I hacked together something that runs the same code as the mod_perl 
thing, and the result is that the bug appears consistently every time.

http://wwwdev.nber.org/cgi-bin/testsched.cgi

Unfortunately I was not able to get CGI parameters passed in because CGI 
and Apache::Request handle parameters differently.

I am pretty sure I was able to remove all use of any Apache:: object 
from this code path.


testobj is a script that instantiates an object of the given class with 
the given id and runs the given method

[aminoff@perlw2 cgi-bin]$ testobj Schedule::Item 4183 is_hash
0
[aminoff@perlw2 cgi-bin]$ testobj Schedule::Item 4183 schedule_time
8:30 am
[aminoff@perlw2 cgi-bin]$ testobj Schedule::Item 4183 confids_links
<a href="http://wwwdev.nber.org/sched/SI17IFM">IFM</a>
[aminoff@perlw2 cgi-bin]$ testobj Schedule::Item 4183 room_always
Charles

[aminoff@perlw2 cgi-bin]$ testobj Schedule::Item 4183 txt

(empty string)

I may try again to add some debugging warn statements to 
Mustache::Simple to try to get info on the state of various variables 
soon before the uninitialized message we are seeing.

  - Alex

**Comment by CliffS** [comment]
The only place that it checks for for whether or not to escape is line 355 of `Mustache/Simple.pm`.  It checks `$tag->{type}` which should be `""` if we started with `{{`.  Or `"{"` for `{{{` (or `"&" for `{{&`).

I can't see anywhere that `$tag->{type}` could get modified between line 319 and line 355.  The whole routine `sub resolve` is called recursively for tags with a dot in them but `my $tag` is set locally so shouldn't be affected.  The only possibility is that `tags[$i]` is somehow being changed as `my $tag` is a reference to that.

Two things you could do:

1. Check the value of `$tag->{type} at line 355 to make sure it's `"{"`.

1. Change line 317 to `my $tag = { %{$tags[$i] }` to force `$tag` to be a clone of `$tags[$i]` rather than a reference to it.

If you wouldn't mind making the second change, I'd be very interested in the result.

**Comment by aaminoff** [comment]
On 04/02/2018 01:15 PM, Cliff Stanford wrote:
>
> The only place that it checks for for whether or not to escape is line 
> 355 of |Mustache/Simple.pm|. It checks |$tag->{type}| which should be 
> |""| if we started with |{{|. Or |"{"| for |{{{| (or |"&" for|{{&`).
>
> I can't see anywhere that |$tag->{type}| could get modified between 
> line 319 and line 355. The whole routine |sub resolve| is called 
> recursively for tags with a dot in them but |my $tag| is set locally 
> so shouldn't be affected. The only possibility is that |tags[$i]| is 
> somehow being changed as |my $tag| is a reference to that.
>
> Two things you could do:
>
> 1.
>
>     Check the value of |$tag->{type} at line 355 to make sure it's|"{"`.
>
> 2.
>
>     Change line 317 to |my $tag = { %{$tags[$i] }| to force |$tag| to
>     be a clone of |$tags[$i]| rather than a reference to it.
>
I did this. It did not appear to have any effect. But it looks to me 
like that is not where the problem occurs.

I added a bunch of debug warn statements.

Let me see if I can describe the crazy thing that happens. I'm putting 
the error log after the statement that produces it, just for the call to 
resolve where the weird thing happens.

> sub resolve
> {
>     my $self = shift;
>     my $context = shift // {};
>     $self->push($context);
>     my @tags = @_;
>     warn "begin resolve with " . scalar(@tags) . " tags\n";
begin resolve with 2 tags
>     my $result = '';
>     for (my $i = 0; $i < @tags; $i++)
>     {
>         my $tag  = { %{ $tags[$i] } };                   # the current tag
>         warn " $tag->{txt} i:$i type:" . $tag->{type} . " txt:" . 
> $tag->{txt} . "\n";
confids_links i:0 type:{ txt:confids_links: 
/homes/web/cgi-bin/testsched.cgi
>
>         $result .= $tag->{pre};                 # add in the 
> intervening text
>         given ($tag->{type})
>         {
>             when('!') {                         # it's a comment
>                 # $result .= $tag->{tab} if $tag->{tab};
>             }
>             when('/') { break; }                # it's a section end - 
> skip
>             when('=') { break; }                # delimiter change
>             when(/^([{&])?$/) {                 # it's a variable
>                 my $txt;
>                 if ($tag->{txt} eq '.')
>                 {
>                     $txt = $self->{stack}->top;
>                 }
>                 elsif ($tag->{txt} =~ /\./)
>                 {
>                     my @dots = dottags $tag->{txt}, $tag->{type};
>                     $txt = $self->resolve(undef, @dots);
>                 }
>                 else {
>                     $txt = $self->find($tag->{txt});    # get the 
> entry from the context
>                     if (defined $txt)
>                     {
>                         if (ref $txt eq 'CODE')
>                         {
>                             my $saved = $self->{delimiters};
>                             $self->{delimiters} = [qw({{ }})];
>                             $txt = $self->render($txt->());
>                             $self->{delimiters} = $saved;
>                         }
>                     }
>                     else {
>                         croak qq(No context for "$tag->{txt}") if 
> $self->throw;
>                         $txt = '';
>                     }
>                 }
>                 warn  " when bracket or ampersand tag type: " . 
> (defined($tag->{type}) ? $tag->{type} : "undefined") . " for tag txt: 
> $tag->{txt}\n";

when bracket or ampersand tag type: undefined for tag txt: confids_links

>                 $txt = "$tag->{tab}$txt" if $tag->{tab};        # 
> replace the indent
>                 $result .= $tag->{type} ? $txt : escape $txt;
>             }

How did $tag->{type} go from "{" to not defined in that span of code? It 
has to be some sort of magic involving given($tag->{type}) when (regexp) ?

I tried replacing the regexp with

            when( $_ eq '{' || $_ eq '&' ) {                 # it's a 
variable

that did not appear to help.


OK, I think I tracked it down more closely:


>                else {
>                     warn "  before self find tag type: " . 
> (defined($tag->{type}) ? $tag->{type} : "undefined") . " for tag txt: 
> $tag->{txt}\n";
before self find tag type: { for tag txt: confids_links
>                     $txt = $self->find($tag->{txt});    # get the 
> entry from the context
>                     warn "  after self find tag type: " . 
> (defined($tag->{type}) ? $tag->{type} : "undefined") . " for tag txt: 
> $tag->{txt}\n";

after self find tag type: undefined for tag txt: confids_links

So somehow $tag->{type} is being clobbered as a side effect of calling 
$self->find.

That is as far as I have time for today. You can play with this at

http://wwwdev.nber.org/cgi-bin/testsched.cgi?template=http://www.nber.org/~aminoff/moreminimal.mtmpl

Pass a URL where a template you want filled in can be downloaded. Then, 
after it runs, scroll down to the bottom and you will see a link "get 
error log". That will give you the error log of that run, with all the 
warn output. This is of course a big security hole but it is temporary.

  - Alex

**Comment by CliffS** [comment]
Sorry it's taken me a while to get back to this and thank you for all the hard work you've put in.

I cannot see any way that `$tag-{type}` can change inside that `when` statement.  However, clearly it does.  How about setting a variable, something like:

```perl
            when(/^([{&])?$/) {                 # it's a variable
                my $txt;
                my $want_escape = $tag->{type} ne ''
                if ($tag->{txt} eq '.')
                {
                    $txt = $self->{stack}->top;
                }
                elsif ($tag->{txt} =~ /\./)
                {
                    my @dots = dottags $tag->{txt}, $tag->{type};
                    $txt = $self->resolve(undef, @dots);
                }
                else {
                    $txt = $self->find($tag->{txt});    # get the entry from the context
                    if (defined $txt)
                    {
                        if (ref $txt eq 'CODE')
                        {
                            my $saved = $self->{delimiters};
                            $self->{delimiters} = [qw({{ }})];
                            $txt = $self->render($txt->());
                            $self->{delimiters} = $saved;
                        }
                    }
                    else {
                        croak qq(No context for "$tag->{txt}") if $self->throw;
                        $txt = '';
                    }
                }
                $txt = "$tag->{tab}$txt" if $tag->{tab};        # replace the indent
                $result .= $want_escape ? $txt : escape $txt;
```
And yes, I'm clutching at straws.

**Comment by aaminoff** [comment]
I ran out of the amount of my employer's time I could spend on this in 
the short term. I hope to get back to this issue next week. I agree that 
your plan should work. I was hoping to try to delve a little deeper and 
try to look inside ->find, but what is really odd is that the problem is 
intermittent, both in that sometimes when I run the code it works 
flawlessly all over, and sometimes when I run the code it produces some 
good rows and some bad rows. Intermittent bugs are the worst.

Things I hope to do, though I am not sure if I will get to any of them:

  - try your proposal. That is easy enough and probably works. Solves 
the problem, but not the mystery.

  - Build an independently-runnable test case that always (or at least 
sometimes) demonstrates the problem. I have set up the thing to run as a 
cgi script, I have not yet set it up to run from the command line. After 
that, I need to organize a set of simple modules that replicates my 
structure that I could tar up and send to someone. My guess is the bug 
won't replicate unless in a very complex environment, because it stems 
from some sort of scope problem or memory-allocation problem deep in perl.

  - Change given/when to much simpler perl control constructs. I think I 
already did this once and the problem still happened, but I was still 
using $_. Basically


   {
      my $it = $tag->{type};

      $it eq '/' and last;

      ...

      if ($it eq '&' || $it eq '{') {

          ...

The only difference is removing the for () { block and removing the use 
of the special variable $_.


I guess the first and third are really easy to try so I will try those 
first. But probably not till Monday or Tuesday.

  - Alex

**Comment by aaminoff** [comment]
I tried the first and third things below - setting a $want_escape 
variable and completely replacing given/when with something much more 
standard, and in both cases, that moved the odd behavior to a different 
place in the code. I don't have time to document in detail where it 
ended up, I will work on that tomorrow I hope.

One thing I could try is change use 5.10.1 at the top to different 
values. I would have to read up on exactly what that use statement does.

>    Also, if the specified perl version is greater than or equal to 5.9.5,
>                "use VERSION" will also load the "feature" pragma and 
> enable all
>                features available in the requested version.  See feature.
>
Perhaps I could turn off certain features one at a time. I probably 
would have to mess with use 5.10.1 and/or features in each of the files 
individually because those are lexically scoped.

**Comment by akrabat** [comment]
The author of this component died in 2022 and this repository is now archived.
