### ISSUE TITLE
Disable file system templates

### ISSUE THREAD

**Issue by remorse** [CliffS/mustache-simple#8]
Hi! Is there a way to disable the ability of the module to find templates on disk? I want to pre-load all of the templates that will be used, and have it fail if for some reason it is asked to find a template that I haven't explicitly told it about...

Thanks,
Ricky

**Comment by CliffS** [comment]
How about not having the templates in the path given to the module?  But I think you're probably worrying about the wrong thing.  The file-system should cache the partials so they're very cheap to load after the first time.

**Comment by akrabat** [comment]
The author of this component died in 2022 and this repository is now archived.
